### ISSUE TITLE
Error: Running the contributed command: 'foxdot.send' failed.

### ISSUE THREAD

**Issue by tiktuk** [yasuyuky/vscode-foxdot#126]
Hi,

I get the error in the title when trying to run a line of Foxdot code using this extension. (The start command seems to execute without errors.)

This was in the logs:

```
[2020-12-26 17:35:56.612] [exthost] [error] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:431:19)
	at writeOrBuffer (_stream_writable.js:419:5)
	at Socket.Writable.write (_stream_writable.js:309:11)
	at sendSelections (/Users/tuk/.vscode/extensions/yasuyuky.vscode-foxdot-0.0.4/out/extension.js:179:73)
	at send (/Users/tuk/.vscode/extensions/yasuyuky.vscode-foxdot-0.0.4/out/extension.js:172:5)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1020:786
	at t.ExtHostTextEditor.edit (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:191)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1020:775
	at _executeContributedCommand (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:701:220)
	at _.$executeContributedCommand (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:701:595)
	at m._doInvokeHandler (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:926)
	at m._invokeHandler (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:618)
	at m._receiveRequest (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:891:252)
	at m._receiveOneMessage (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:890:6)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:888:136
	at l.fire (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1094:104
	at l.fire (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:1004)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:927
	at l.fire (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at p.acceptChunk (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:231:195)
	at /Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:547
	at Socket.t (/Users/tuk/Casks/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) foxdot.send
```

Foxdot's own editor works fine.

Thanks for making the extension!

**Comment by yasuyuky** [comment]
I don't know the details because I can't reproduce it in my environment, but I'm guessing it's probably because FoxDot is not starting.

I've added [some simple instructions](https://github.com/yasuyuky/vscode-foxdot/blob/main/STARTUP.macos.md) to help you set it up, which may be helpful.
